### ISSUE TITLE
Error when running the tool without any parameters

### ISSUE THREAD

**Issue by sayedihashimi** [jmprieur/app-provisonning-tool#24]
When I run the tool (either the latest version from [this branch](https://github.com/AzureAD/microsoft-identity-web/tree/jennyf/proviTool/tools/app-provisioning-tool) or the version in this repo), I get an error message. I think the error messages from both versions of the tool are the same but I haven't compared them. Below is the error message that I'm getting after running the tool without any parameters. This was working yesterday, not sure what happened on my machine since then. I made sure to be signed into VS with a single account that has access to create Azure objects. If you need the project that I was working with it is [here](https://www.dropbox.com/s/csl6t10lm814pge/WebApp.zip?dl=0). I tried with projects created using Visual Studio and the `dotnet new` cli.

```
ms-identity-app
Detected dotnet-webapp.
Unhandled exception: Status Code: 0
Microsoft.Graph.ServiceException: Code: generalException
Message: An error occurred sending the request.

 ---> MSAL.NetCore.4.22.0.0.MsalServiceException:
        ErrorCode: invalid_request
                                  Microsoft.Identity.Client.MsalServiceException: AADSTS90002: Tenant '22222222-2222-2222-2222-222222222222' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.
Trace ID: 32837f2a-072d-45b8-81fb-d518afb21e00
Correlation ID: ec4d9a7e-5b6a-44db-920f-e09a3333dd50
Timestamp: 2021-02-18 21:16:21Z
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext, Boolean addCommonHeaders)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.SendTokenRequestAsync(String tokenEndpoint, IDictionary`2 additionalBodyParameters, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.RefreshAccessTokenAsync(MsalRefreshTokenCacheItem msalRefreshTokenItem, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.TryGetTokenUsingFociAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.RefreshRtOrFailAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ClientApplicationBaseExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenSilentParameters silentParameters, CancellationToken cancellationToken)
   at DotnetTool.DeveloperCredentials.MsalTokenCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken) in D:\data\mycode\OSS\microsoft-identity-web\tools\app-provisioning-tool\app-provisioning-lib\DeveloperCredentials\MsalTokenCredential.cs:line 93
   at DotnetTool.MicrosoftIdentityPlatformApplication.TokenCredentialAuthenticationProvider.AuthenticateRequestAsync(HttpRequestMessage request) in D:\data\mycode\OSS\microsoft-identity-web\tools\app-provisioning-tool\app-provisioning-lib\MicrosoftIdentityPlatformApplication\TokenCredentialAuthenticationProvider.cs:line 37
   at Microsoft.Graph.AuthenticationHandler.SendAsync(HttpRequestMessage httpRequestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Microsoft.Graph.HttpProvider.SendRequestAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
        StatusCode: 400
        ResponseBody: {"error":"invalid_request","error_description":"AADSTS90002: Tenant '22222222-2222-2222-2222-222222222222' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.\r\nTrace ID: 32837f2a-072d-45b8-81fb-d518afb21e00\r\nCorrelation ID: ec4d9a7e-5b6a-44db-920f-e09a3333dd50\r\nTimestamp: 2021-02-18 21:16:21Z","error_codes":[90002],"timestamp":"2021-02-18 21:16:21Z","trace_id":"32837f2a-072d-45b8-81fb-d518afb21e00","correlation_id":"ec4d9a7e-5b6a-44db-920f-e09a3333dd50","error_uri":"https://login.microsoftonline.com/error?code=90002"}
        Headers: Cache-Control: no-store, no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
client-request-id: ec4d9a7e-5b6a-44db-920f-e09a3333dd50
x-ms-request-id: 32837f2a-072d-45b8-81fb-d518afb21e00
x-ms-ests-server: 2.1.11496.7 - WUS2 ProdSlices
x-ms-clitelem: 1,90002,0,218607.4833,
Set-Cookie: fpc=An7nvhKcRbJMtk-Hf1dXQycPUIHkAQAAACXQwNcOAAAA; expires=Sat, 20-Mar-2021 21:16:21 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=prod; path=/; secure; httponly, stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Date: Thu, 18 Feb 2021 21:16:21 GMT

   --- End of inner exception stack trace ---
   at Microsoft.Graph.HttpProvider.SendRequestAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.GraphServiceOrganizationCollectionRequest.GetAsync(CancellationToken cancellationToken)
   at DotnetTool.MicrosoftIdentityPlatformApplication.MicrosoftIdentityPlatformApplicationManager.ReadApplication(TokenCredential tokenCredential, ApplicationParameters applicationParameters) in D:\data\mycode\OSS\microsoft-identity-web\tools\app-provisioning-tool\app-provisioning-lib\MicrosoftIdentityPlatformApplication\MicrosoftIdentityPlatformApplicationManager.cs:line 526
   at DotnetTool.AppProvisioningTool.ReadOrProvisionMicrosoftIdentityApplication(TokenCredential tokenCredential, ApplicationParameters applicationParameters) in D:\data\mycode\OSS\microsoft-identity-web\tools\app-provisioning-tool\app-provisioning-lib\Tool\AppProvisioningTool.cs:line 158
   at DotnetTool.AppProvisioningTool.Run() in D:\data\mycode\OSS\microsoft-identity-web\tools\app-provisioning-tool\app-provisioning-lib\Tool\AppProvisioningTool.cs:line 74
   at DotnetTool.Program.Main(String tenantId, String username, String clientId, Nullable`1 unregister, String folder, String clientSecret) in D:\data\mycode\OSS\microsoft-identity-web\tools\app-provisioning-tool\app-provisioning-tool\Program.cs:line 53
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass6_0.<<ConfigureConsole>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by sayedihashimi** [comment]
After playing with this for a bit I tried to see if the following command would work `ms-identity-app --username sayedha@microsoft.com`. When I did that, the browser opened and it looks like it's trying to get the tenant with the stub ID in `appSettings.json` (22222222-2222-2222-2222-222222222222). This is the ID that we put into the appSettings.json file, we shouldn't try to find that

`
Request Id: da7c38c2-0610-4d66-91b3-1eb7b1fd1501
Correlation Id: d8731aa4-1b58-4566-a6a2-a2460a581f65
Timestamp: 2021-02-18T21:48:22Z
Message: AADSTS90002: Tenant '22222222-2222-2222-2222-222222222222' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.
`

**Comment by jennyf19** [comment]
@sayedihashimi I believe this [pr](https://github.com/AzureAD/microsoft-identity-web/pull/988/files) fixed the issue, which is in master now.

**Comment by sayedihashimi** [comment]
Thanks, I will try it out tomorrow.

**Comment by sayedihashimi** [comment]
@jennyf19 I tried the latest in the master branch from https://github.com/AzureAD/microsoft-identity-web, and I also tried the nuget package from [this build](https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=735796&view=artifacts&pathAsName=false&type=publishedArtifacts). I'm no longer getting the `invalid_request`, but instead now I get `invalid_client`. I am seeing this on two different machines (1 a VM on my physical box).

```
ms-identity-app
Detected dotnet-webapp.
Unhandled exception: Status Code: 0
Microsoft.Graph.ServiceException: Code: generalException
Message: An error occurred sending the request.

 ---> MSAL.NetCore.4.22.0.0.MsalServiceException:
        ErrorCode: invalid_client
                                 Microsoft.Identity.Client.MsalServiceException: A configuration issue is preventing authentication - check the error message from the server for details.You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS70002: The client does not exist or is not enabled for consumers. If you are the application developer, configure a new application through the App Registrations in the Azure Portal at https://go.microsoft.com/fwlink/?linkid=2083908.
Trace ID: 1dc312f7-fc82-4beb-aea7-758200321c00
Correlation ID: 59cb6442-24e4-4750-b532-d8e78541e808
Timestamp: 2021-02-19 17:36:18Z
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext, Boolean addCommonHeaders)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.SendTokenRequestAsync(String tokenEndpoint, IDictionary`2 additionalBodyParameters, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.RefreshAccessTokenAsync(MsalRefreshTokenCacheItem msalRefreshTokenItem, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.TryGetTokenUsingFociAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.RefreshRtOrFailAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ClientApplicationBaseExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenSilentParameters silentParameters, CancellationToken cancellationToken)
   at Microsoft.Identity.App.DeveloperCredentials.MsalTokenCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken) in D:\data\mycode\OSS\microsoft-identity-web\tools\app-provisioning-tool\app-provisioning-lib\DeveloperCredentials\MsalTokenCredential.cs:line 95
   at Microsoft.Identity.App.MicrosoftIdentityPlatformApplication.TokenCredentialAuthenticationProvider.AuthenticateRequestAsync(HttpRequestMessage request) in D:\data\mycode\OSS\microsoft-identity-web\tools\app-provisioning-tool\app-provisioning-lib\MicrosoftIdentityPlatformApplication\TokenCredentialAuthenticationProvider.cs:line 36
   at Microsoft.Graph.AuthenticationHandler.SendAsync(HttpRequestMessage httpRequestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Microsoft.Graph.HttpProvider.SendRequestAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
        StatusCode: 401
        ResponseBody: {"error":"invalid_client","error_description":"AADSTS70002: The client does not exist or is not enabled for consumers. If you are the application developer, configure a new application through the App Registrations in the Azure Portal at https://go.microsoft.com/fwlink/?linkid=2083908.\r\nTrace ID: 1dc312f7-fc82-4beb-aea7-758200321c00\r\nCorrelation ID: 59cb6442-24e4-4750-b532-d8e78541e808\r\nTimestamp: 2021-02-19 17:36:18Z","error_codes":[70002],"timestamp":"2021-02-19 17:36:18Z","trace_id":"1dc312f7-fc82-4beb-aea7-758200321c00","correlation_id":"59cb6442-24e4-4750-b532-d8e78541e808","error_uri":"https://login.microsoftonline.com/error?code=70002"}
        Headers: Cache-Control: no-store, no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
client-request-id: 59cb6442-24e4-4750-b532-d8e78541e808
x-ms-request-id: 1dc312f7-fc82-4beb-aea7-758200321c00
x-ms-ests-server: 2.1.11496.7 - WUS2 ProdSlices
x-ms-clitelem: 1,70002,0,128438.111,
Set-Cookie: fpc=Ah_S8g1HfCZHrL99xcfbflRPHGiLAQAAABHuwdcOAAAA; expires=Sun, 21-Mar-2021 17:36:18 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=prod; path=/; secure; httponly, stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Date: Fri, 19 Feb 2021 17:36:17 GMT

   --- End of inner exception stack trace ---
   at Microsoft.Graph.HttpProvider.SendRequestAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.GraphServiceOrganizationCollectionRequest.GetAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.App.MicrosoftIdentityPlatformApplication.MicrosoftIdentityPlatformApplicationManager.CreateNewApp(TokenCredential tokenCredential, ApplicationParameters applicationParameters) in D:\data\mycode\OSS\microsoft-identity-web\tools\app-provisioning-tool\app-provisioning-lib\MicrosoftIdentityPlatformApplication\MicrosoftIdentityPlatformApplicationManager.cs:line 27
   at Microsoft.Identity.App.AppProvisioningTool.ReadOrProvisionMicrosoftIdentityApplication(TokenCredential tokenCredential, ApplicationParameters applicationParameters) in D:\data\mycode\OSS\microsoft-identity-web\tools\app-provisioning-tool\app-provisioning-lib\Tool\AppProvisioningTool.cs:line 167
   at Microsoft.Identity.App.AppProvisioningTool.Run() in D:\data\mycode\OSS\microsoft-identity-web\tools\app-provisioning-tool\app-provisioning-lib\Tool\AppProvisioningTool.cs:line 74
   at Microsoft.Identity.App.Program.Main(String tenantId, String username, String clientId, String folder, String clientSecret, Nullable`1 unregister) in D:\data\mycode\OSS\microsoft-identity-web\tools\app-provisioning-tool\app-provisioning-tool\Program.cs:line 63
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass6_0.<<ConfigureConsole>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by jmprieur** [comment]
@sayedihashimi
Can you provide repro steps?

```Shell
dotnet new xxx --auth SingleOrg ?
```

- With which options did you run the tool?
- Which account did you use?  would it be a personal account?

**Comment by sayedihashimi** [comment]
@jmprieur same as in the readme here `dotnet new webapp --auth SingleOrg`, in the issue I included a link to the project that I used, but this repros with new projects as well.
I executed the tool with no parameters, and also tried passing in `--username sayedha@outlook.com`. Personal account that has ability to create things in Azure.

**Comment by jennyf19** [comment]
@sayedihashimi Can you try with this [branch](https://github.com/AzureAD/microsoft-identity-web/tree/jennyf/updateOrg) and see if the error repros there as well? thanks.

**Comment by jennyf19** [comment]
@sayedihashimi also, you might want to uninstall the tool first:
```@shell
dotnet tool uninstall --global ms-identity-app
dotnet pack
dotnet tool install --global --add-source app-provisioning-tool\nupkg ms-identity-app
```

**Comment by sayedihashimi** [comment]
Hi @jennyf19, yes I did uninstall the tool before hand. I actually created a script so that I don't need to remember that. Pasted it below in case you want to use it as well. It has a dependency on another tool that I created, but I included the command to get it installed.

I tried on the branch you specified (https://github.com/AzureAD/microsoft-identity-web/tree/jennyf/updateOrg). I also manually updated the version to a higher value because I thought there may be a nuget cache giving me a stale .nupkg but that didn't seem to help either.

Maybe we should jump on a call so that I can show you what's happening on my end?

```
function Reset-WebProvisionTool{
    [cmdletbinding()]
    param(
        [string]$folderPath = (join-path $codeHome OSS\microsoft-identity-web)
    )
    process{
        Push-Location $folderPath
        # delete all bin/obj/nupkg folders to ensure we get a clean build
        # this tool can be installed with: dotnet tool install --global SayedHa.Commands --version 1.0.3
        sayedha removefolders -f bin -f obj -f nupkg 
        'calling dotnet pack' | Write-Output
        dotnet pack .\tools\app-provisioning-tool\app-provisioning-tool\ms-identity-app.csproj
        'uninstall template' | Write-Output
        dotnet tool uninstall -g ms-identity-app
        'install template' | Write-Output
        dotnet tool install -g --add-source .\tools\app-provisioning-tool\app-provisioning-tool\nupkg\ ms-identity-app
        Pop-Location
    }
}
```

**Comment by sayedihashimi** [comment]
I also tried it with a different azure account, that I created a while back but haven't done much with. Same result.
